CREATE DATABASE spacextodo;

CREATE TABLE todos(
id BIGSERIAL NOT NULL PRIMARY KEY,
todo_owner VARCHAR(100) NOT NULL REFERENCES users(email),
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
todo VARCHAR(150) NOT NULL,
description VARCHAR(200),
colab VARCHAR(150)
);

CREATE TABLE users (
id BIGSERIAL NOT NULL PRIMARY KEY,
name VARCHAR(150) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE 
)